name: CDXGen

on: workflow_dispatch

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: "Checout code"
        uses: actions/checkout@v4
  
      - name: "Check input"
        shell: bash
        run: |
          if [[ "${{ inputs.project_type }}" != "" ]]
          then
            echo "Project type is provided: ${{ inputs.project_type }}"
            echo "PROJECT_TYPE=-t ${{ inputs.project_type }}" >> $GITHUB_ENV
          else
            echo "Project type is not provided"
            echo "PROJECT_TYPE=" >> $GITHUB_ENV
          fi
  
      - name: "Generate Depscan report"
        run: |
          cd ${GITHUB_WORKSPACE}
          docker run --rm -v $PWD:/app ghcr.io/owasp-dep-scan/dep-scan \
          --src /app --reports-dir /app/reports
        shell: bash
      - name: "Debug"
        run: |
          ls -la ./
      - name: "Upload Depscan report"
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: "DEPSCAN report"
          path: ${{ github.workspace }}/reports/*
          retention-days: 5

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/reports/

  # Deployment job
  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: "Summary"
        run: |
          echo "${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
